name: 'Build and Push'
author: 'Developer Experience Team'
description: 'Build a Dockerfile to an image and pushes it to Harbor.'
inputs:
  project:
    description: 'Project where the image must be uploaded to the container registry.'
    required: false
  buildArgs:
    description: 'Command arguments to be appended to the build command.'
    required: false
  dockerfile:
    description: 'Filepath of the Dockerfile.'
    required: false
    default: './Dockerfile'
  imageNameSuffix:
    description: 'Suffix to be appended to the image name.'
    required: false
  tags:
    description: 'List of tags (example: "tag1;tag2;tag3")'
    required: false
    default: ""

runs:
  using: 'composite'
  steps:
    - shell: bash
      if: runner.os == 'Linux'
      run: ${{ github.action_path }}/build-and-push.sh
      env:
        PROJECT: ${{ inputs.project }}
        BUILD_ARGS: ${{ inputs.buildArgs }}
        DOCKERFILE: ${{ inputs.dockerfile }}
        IMAGE_NAME_SUFFIX: ${{ inputs.imageNameSuffix }}
        TAGS: ${{ inputs.tags }}