name: 'Deploy on K8s Cluster'
author: 'Developer Experience Team'
description: 'Deploy an application on a k8s cluster'
inputs:
  namespace:
    description: 'Namespace for deploy'
    required: false
  manifest:
    description: 'Path to manifest deploy'
    required: false
  config:
    description: 'Kubectl configuration file'
    required: false
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: ${{ github.action_path }}/deploy-k8s/deploy-k8s.sh
      env:
        NAMESPACE: ${{ inputs.namespace }}
        MANIFEST: ${{ inputs.manifest }}
        CONFIG: ${{ inputs.config }}
